title: Cloudstream Systems
email: cephaskudalor05@gmail.com
description: >-
  A personal portfolio built with Jekyll and Minima.
theme: minima
minima:
  skin: auto
  head_custom: head-custom.html
  footer_custom: footer-custom.html

# Social Media Links
github_username: cloudstreamsystems
twitter_username: cloudstreamsys
linkedin_username: cloudstreamsystems
instagram_username: cloudstreamsystems

# Author Information
author:
  name: Cloudstream Systems
  email: cephaskudalor05@gmail.com
  location: Accra, Ghana
  bio: "Full-stack developer passionate about creating innovative web solutions"

sass:
  style: compressed

include:
  - include:
  - assets
  - assets/main.css

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-include-cache

navigation:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "Projects"
    url: /projects/