title: Cloudstream Systems
email: cephaskudalor05@gmail.com
description: >-
  a portfolio built with jekyll and minima

# Local Development Configuration
host: 127.0.0.1
port: 4000
url: ""
baseurl: ""
livereload: true
incremental: false

# Social Media Links
github_username: cloudstreamsystems
twitter_username: cloudstreamsys
linkedin_username: cloudstreamsystems
instagram_username: cloudstreamsystems

# Author Information
author:
  name: Cloudstream Systems
  email: cephaskudalor05@gmail.com
  location: Accra, Ghana
  bio: "Full-stack developer passionate about creating innovative web solutions"

sass:
  style: compressed

include:
  - assets
  - assets/main.css

navigation:
  - title: "About Us"
    url: /about/
  - title: "Projects"
    url: /projects/
  - title: "Contact Us"
    url: /contact/