title: Cloudstream Systems
email: cephaskudalor05@gmail.com
description: >-
  A personal portfolio built with Jekyll and Minima.
theme: minima
minima:
  skin: auto
  head_custom: head-custom.html

sass:
  style: compressed

include:
  - include:
  - assets
  - assets/main.css

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-include-cache

navigation:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "Projects"
    url: /projects/